apiVersion: v1
kind: Secret
metadata:
  name: prodavnica-mariadb-secret
  namespace: ar-web-namespace
type: Opaque
stringData:
  MARIADB_ROOT_PASSWORD: ${PRODAVNICA_DB_ROOT_PASSWORD}
  MARIADB_DATABASE: wordpress
  MARIADB_USER: wordpress
  MARIADB_PASSWORD: ${PRODAVNICA_DB_PASSWORD}
