apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prodavnica-mariadb-pvc
  namespace: ar-web-namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
