apiVersion: v1
kind: Secret
metadata:
  name: prodavnica-wordpress-secret
  namespace: ar-web-namespace
type: Opaque
stringData:
  WORDPRESS_DB_HOST: prodavnica-mariadb-service:3306
  WORDPRESS_DB_NAME: wordpress
  WORDPRESS_DB_USER: wordpress
  WORDPRESS_DB_PASSWORD: ${PRODAVNICA_DB_PASSWORD}
