apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prodavnica-wordpress-pvc
  namespace: ar-web-namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
