apiVersion: v1
kind: Service
metadata:
  name: ${DEPLOY_ENV}-ar-web-fe-service
  namespace: ar-web-namespace
spec:
  selector:
    app: ${DEPLOY_ENV}-ar-web-fe
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort