name: Deploy aleksaristic-web-fe application to cluster
on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
jobs:
  apply-resources:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    steps:
    - uses: actions/checkout@v3

    - name: Set K8s context
      uses: ossrs/k8s-set-context-action@v1
      with:
        kubeconfig: '${{ secrets.KUBE_CONFIG_PURE }}'
    - name: Deploy aleksaristic-web-fe application
      run: |-
        export DEPLOY_ENV=${{ inputs.env }}
        envsubst < k8s/services/ar-web-fe-service.yaml | kubectl apply -f -
        envsubst < k8s/deployments/ar-web-fe-deployment.yaml | kubectl apply -f -
        envsubst < k8s/ingress/ar-web-ingress.yaml | kubectl apply -f -
        envsubst < k8s/ingress/root-ingress.yaml | kubectl apply -f -
        kubectl rollout restart -n ar-web-namespace deployment ${{ inputs.env }}-ar-web-fe-deployment