name: Release production aleksaristic-web

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]

jobs:
  public-api:
    uses: DoLoop216/aleksaristic-ecosystem/.github/workflows/build-and-publish-web-fe.yml@master
    secrets: inherit
    with:
      env: production